### ISSUE TITLE
[CWE-89] SQL Injection in stock.php, Line 23/24/33

### ISSUE THREAD

**Issue by March-M** [GnomeZworc/trcp-public-frontend#11]
Hello,

### Issue

There is multiples clear SQL injection in file stock.php, line 23, 24 and 33, due to an improper validation of the get parameter "id", passed directly to the SQL command line.

### Remediation

I would recommend you to globally stop the insecure way of doing SQL connexion \*\*_query and migrate over a PDO connexion. Those are way more secure and made to avoid any SQL injection as they handle the construction of the SQL request in a per-design safe way.
The hot-fix (that shouldn't be considered as definitive fix but that can fix the issue right now) would be to validate the content of the "id" variable, in this case you could just pass it to the php function "intval" who can ensure there isn't anything else than number in it.

**Comment by GnomeZworc** [comment]
thanks for the help
