### ISSUE TITLE
[CWE-89] SQL Injection in submit.php, Line 36

### ISSUE THREAD

**Issue by March-M** [GnomeZworc/trcp-public-frontend#13]
Hello,

### Issue

There is a clear SQL injection in file submit.php, line 36, due to an improper validation of the php variable "uuid", who is generated by the code on line 26 to 30 of the same page from an unfiltered get parameter named "uuid", and passed directly to the SQL command line.

### Remediation

I would recommend you to globally stop the insecure way of doing SQL connexion \*\*_query and migrate over a PDO connexion. Those are way more secure and made to avoid any SQL injection as they handle the construction of the SQL request in a per-design safe way.
The hot-fix (that shouldn't be considered as definitive fix but that can fix the issue right now) would be to validate the content of the "uuid" get/post variable, in this case you could just check if the uuid parameter match a regex that can confirm it's a syntax-valid UUID (cf: https://stackoverflow.com/questions/12808597/php-verify-valid-uuid), and not using it if it doesn't match the regex.

**Comment by GnomeZworc** [comment]
Thanks for the help
