### ISSUE TITLE
[CWE-89] POST based SQL Injection in submit.php, Line 16

### ISSUE THREAD

**Issue by March-M** [GnomeZworc/trcp-public-frontend#14]
Hello,

### Issue

There is a clear SQL injection in file submit.php, line 16, due to an improper validation of the post variable "email", who is passed directly to the SQL command line.

### Remediation

I would recommend you to globally stop the insecure way of doing SQL connexion \*\*_query and migrate over a PDO connexion. Those are way more secure and made to avoid any SQL injection as they handle the construction of the SQL request in a per-design safe way.
The hot-fix (that shouldn't be considered as definitive fix but that can fix the issue right now) would be to validate the content of the "email" post variable, in this case you could just check if the email parameter match a regex that can confirm it's a syntax-valid email that respect the corresponding RFC's (cf: https://datatracker.ietf.org/doc/html/rfc2822), and not using it if it doesn't match the regex.

**Comment by draescherl** [comment]
To add on @March-M's comment, another temporary fix could be to use `pg_query_params` rather than `pg_query`. [Doc here.](https://www.php.net/manual/fr/function.pg-query-params.php)

**Comment by GnomeZworc** [comment]
Thanks for the help
